### ISSUE TITLE
Supported SSL version?

### ISSUE THREAD

**Issue by stefanheijnen** [BitCannaGlobal/BCNA_bitcore_old#1]
Hi,

What is the supported openssl version? I'm building on Manjaro (Arch based) and I get this error:

`configure: error: Detected unsupported SSL version: This is NOT supported, and may break consensus compatibility! Use '--with-unsupported-ssl' if you don't care`

```
openssl version
OpenSSL 1.1.1b  26 Feb 2019
```

**Comment by hellresistor** [comment]
30th July. Have updated code. I think so

**Comment by BitCannaGlobal** [comment]
Hi @stefanheijnen,

Need to use OpenSSL 1.0.2r

Best regards,
BitCanna team
