### ISSUE TITLE
Crash when no wallet.dat available

### ISSUE THREAD

**Issue by stefanheijnen** [BitCannaGlobal/BCNA_bitcore_old#3]
When there is no wallet.dat available, bitcanna crashes. I've tested with cli and qt.

qt:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  CDB : Error 2, can't open database 
Aborted (core dumped)
```

cli:
```
************************
EXCEPTION: St13runtime_error       
CDB : Error 2, can't open database        
bitcanna in AppInit()  
```

db.log:

`/home/bitcanna/.bitcanna/wallet.dat: No such file or directory`

**Comment by stefanheijnen** [comment]
I found a workaround in the masternode guide:

Step 4 - Remove masternode.conf file
• You must remove the masternode.conf file since we need the wallet to create a new one at a later stage. You can remove the masternode.conf file by using the following command: rm~/.bitcanna/masternode.conf

Step 5 - Create wallet.dat file
• The wallet.dat file will be created automatically if you restart the daemon – run: ./bitcannad -daemon

**Comment by BitCannaGlobal** [comment]
Hello @stefanheijnen,

This is fixed in [release v.1.0.1](https://github.com/BitCannaGlobal/BCNA/releases/tag/1.0.1)
