### ISSUE TITLE
Does not respect ‘-onlynet=ipv6’

### ISSUE THREAD

**Issue by kseistrup** [BitCannaGlobal/BCNA_bitcore_old#4]
When I start `bitcannad` with `-onlynet=ipv6`, or have `onlynet=ipv6` in `bitcanna.conf`, I expect `bitcannad` to only connect to IPv6 nodes. Instead I see it connect to IPv6 _and_ IPv4 nodes.

My bitcannad is running on Linux (x86_64), so even if it binds to `[::]` only – because of `bind=[::]` in the configuration file – it can still do IPv4 connections on the socket. In order to prevent IPv4 traffic I currently have to `iptable` the standard port.

**Comment by BitCannaGlobal** [comment]
Hello @kseistrup,

Option '-onlynet=ipv6' isn't supported for now.

Best regards,
BitCanna Team

**Comment by kseistrup** [comment]
> Option ‘-onlynet=ipv6’ isn't supported for now.

Then why not remove it entirely from the long list options shown in `bitcannad --help`, rather than having frustrated users?

And why not keep this issue open so that you won't forget to implement the option? Now everyone is just gonna forget the issue was ever there.

**Comment by BitCannaGlobal** [comment]
Hi Klaus,

We highly appreciate your feedback. I will forward it to our developers.

Thank you.
